### PR TITLE
[qtmozembed] Send screen properties. Fixes JB#56165 OMP#JOLLA-502

### PR DESCRIPTION
**Pull request by mkenttala**

### CODE REVIEW

**Review by rainemak — APPROVED** [review]

**Review by rainemak — CHANGES_REQUESTED** [review]
Changed my mind my apologies. Realized this after checking https://github.com/sailfishos/gecko-dev/pull/98 that EmbedLiteView should have SetScreenProperties as well so that we'd Send all the properties with one Send from parent to child.

**Comment by mkenttala** [comment]
Combined the screen properties.

**Review by rainemak — APPROVED** [review]
Didn't test on device but change looks good now.

**Comment by rainemak** [comment]
I'd just say "Fixes JB#56165 OMP#JOLLA-502" in the commit and merged commit messages as that is what this does.

**Review by okodron — APPROVED** [review]

**Pull request merged**
