### PR TITLE
[qtmozembed] Use appropriate state values from nsIWebProgressListener. Contributes to JB#54949

### PR DESCRIPTION
**Pull request by chriadam**

### CODE REVIEW

**Comment by chriadam** [comment]
Requires building against https://github.com/sailfishos/gecko-dev/tree/sailfishos-esr78-x86base-chriadam

**Comment by llewelld** [comment]
I started out looking at this but got stuck as the required code in the [gecko branch](https://github.com/sailfishos/gecko-dev/tree/sailfishos-esr78-x86base-chriadam) refused to link. I guess you were only using the branch to build the qtmozembed code against, rather then for actually building? At any rate, the following PR updates the gecko branch so that it will build:

https://github.com/sailfishos/gecko-dev/pull/7

I'm hoping this can help with the testing of the qtmozembed changes here.

**Comment by llewelld** [comment]
There's a new enum value `nsITransportSecurityInfo::TLS_VERSION_1_3 = 4`. Would it make sense to add that in here too (+ assert in qmozsecurity.cpp)? It will build without, but arguably is related?

**Review by rainemak — APPROVED** [review]
Builds now. Let's do more PRs if there are more issues. Hence, LGTM.

**Comment by rainemak** [comment]
Please rebase, fix conflict, and merge

**Review by okodron — APPROVED** [review]

**Pull request merged**
