### PR TITLE
[qtmozembed] Changes needed to support ESR 91

### PR DESCRIPTION
**Pull request by llewelld**
Updates the spec file and makes minor chnages to support the updated ESR 91 gecko API.

This is an ESR 91 change, so currently in draft to prevent it being merged.

### CODE REVIEW

**Comment by rainemak** [comment]
@llewelld could we redirect this to sailfishos:sailfishos-esr91 branch instead?

**Comment by llewelld** [comment]
Of course... Done!

**Review by rainemak — APPROVED** [review]
Approving. Let's get this one merged to sailfishos-esr91 and create more PRs on top.

Feel free to merge.

**Review by rainemak — APPROVED** [review]
Still LGTM.

**Pull request merged**
